# Generated by Django 4.2.3 on 2023-07-09 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierform',
            name='products',
        ),
        migrations.AddField(
            model_name='supplierform',
            name='product_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierform',
            name='product_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
