# Generated by Django 4.2.3 on 2023-07-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_supplierform_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierform',
            name='verified_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supplierform',
            name='accreditation_active_status',
            field=models.BooleanField(default=False),
        ),
    ]
