# Generated by Django 4.2.3 on 2023-07-09 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_remove_supplierform_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierform',
            name='Laboratory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.laboratory'),
        ),
        migrations.DeleteModel(
            name='LaboratoryPage',
        ),
    ]
