# Generated by Django 4.2.3 on 2023-07-12 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_supplierform_verified_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierform',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.customer'),
        ),
    ]
