# Generated by Django 4.2.3 on 2023-07-09 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_supplierform_laboratory_delete_laboratorypage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
    ]
