# Generated by Django 4.2.3 on 2023-07-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_supplierform_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierform',
            name='accreditation_name',
            field=models.CharField(choices=[('startupindia', 'startupindia'), ('asme', 'asme')], default='asme', max_length=100),
        ),
    ]
