# Generated by Django 4.2.3 on 2023-07-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_supplierform_test_result_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
