# Generated by Django 4.2.3 on 2023-07-09 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierform',
            name='certificate_image',
            field=models.FileField(upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='supplierform',
            name='product_image',
            field=models.FileField(upload_to='products/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='supplierform',
            name='sub_proof',
            field=models.FileField(upload_to='proof/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='supplierform',
            name='test_result_image',
            field=models.FileField(blank=True, upload_to='result/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
